import { Item } from '../../types';

export const hiragana: Item[] = [
  { id: 'kana-h1', type: 'vocabulary', level: 0, character: 'あ', readings: ['a'], meanings: ['A'], explanation: 'Hiragana: a' },
  { id: 'kana-h2', type: 'vocabulary', level: 0, character: 'い', readings: ['i'], meanings: ['I'], explanation: 'Hiragana: i' },
  { id: 'kana-h3', type: 'vocabulary', level: 0, character: 'う', readings: ['u'], meanings: ['U'], explanation: 'Hiragana: u' },
  { id: 'kana-h4', type: 'vocabulary', level: 0, character: 'え', readings: ['e'], meanings: ['E'], explanation: 'Hiragana: e' },
  { id: 'kana-h5', type: 'vocabulary', level: 0, character: 'お', readings: ['o'], meanings: ['O'], explanation: 'Hiragana: o' },
  { id: 'kana-h6', type: 'vocabulary', level: 0, character: 'か', readings: ['ka'], meanings: ['KA'], explanation: 'Hiragana: ka' },
  { id: 'kana-h7', type: 'vocabulary', level: 0, character: 'き', readings: ['ki'], meanings: ['KI'], explanation: 'Hiragana: ki' },
  { id: 'kana-h8', type: 'vocabulary', level: 0, character: 'く', readings: ['ku'], meanings: ['KU'], explanation: 'Hiragana: ku' },
  { id: 'kana-h9', type: 'vocabulary', level: 0, character: 'け', readings: ['ke'], meanings: ['KE'], explanation: 'Hiragana: ke' },
  { id: 'kana-h10', type: 'vocabulary', level: 0, character: 'こ', readings: ['ko'], meanings: ['KO'], explanation: 'Hiragana: ko' },
  { id: 'kana-h11', type: 'vocabulary', level: 0, character: 'さ', readings: ['sa'], meanings: ['SA'], explanation: 'Hiragana: sa' },
  { id: 'kana-h12', type: 'vocabulary', level: 0, character: 'し', readings: ['shi'], meanings: ['SHI'], explanation: 'Hiragana: shi' },
  { id: 'kana-h13', type: 'vocabulary', level: 0, character: 'す', readings: ['su'], meanings: ['SU'], explanation: 'Hiragana: su' },
  { id: 'kana-h14', type: 'vocabulary', level: 0, character: 'せ', readings: ['se'], meanings: ['SE'], explanation: 'Hiragana: se' },
  { id: 'kana-h15', type: 'vocabulary', level: 0, character: 'そ', readings: ['so'], meanings: ['SO'], explanation: 'Hiragana: so' },
  { id: 'kana-h16', type: 'vocabulary', level: 0, character: 'た', readings: ['ta'], meanings: ['TA'], explanation: 'Hiragana: ta' },
  { id: 'kana-h17', type: 'vocabulary', level: 0, character: 'ち', readings: ['chi'], meanings: ['CHI'], explanation: 'Hiragana: chi' },
  { id: 'kana-h18', type: 'vocabulary', level: 0, character: 'つ', readings: ['tsu'], meanings: ['TSU'], explanation: 'Hiragana: tsu' },
  { id: 'kana-h19', type: 'vocabulary', level: 0, character: 'て', readings: ['te'], meanings: ['TE'], explanation: 'Hiragana: te' },
  { id: 'kana-h20', type: 'vocabulary', level: 0, character: 'と', readings: ['to'], meanings: ['TO'], explanation: 'Hiragana: to' },
  { id: 'kana-h21', type: 'vocabulary', level: 0, character: 'な', readings: ['na'], meanings: ['NA'], explanation: 'Hiragana: na' },
  { id: 'kana-h22', type: 'vocabulary', level: 0, character: 'に', readings: ['ni'], meanings: ['NI'], explanation: 'Hiragana: ni' },
  { id: 'kana-h23', type: 'vocabulary', level: 0, character: 'ぬ', readings: ['nu'], meanings: ['NU'], explanation: 'Hiragana: nu' },
  { id: 'kana-h24', type: 'vocabulary', level: 0, character: 'ね', readings: ['ne'], meanings: ['NE'], explanation: 'Hiragana: ne' },
  { id: 'kana-h25', type: 'vocabulary', level: 0, character: 'の', readings: ['no'], meanings: ['NO'], explanation: 'Hiragana: no' },
  { id: 'kana-h26', type: 'vocabulary', level: 0, character: 'は', readings: ['ha'], meanings: ['HA'], explanation: 'Hiragana: ha' },
  { id: 'kana-h27', type: 'vocabulary', level: 0, character: 'ひ', readings: ['hi'], meanings: ['HI'], explanation: 'Hiragana: hi' },
  { id: 'kana-h28', type: 'vocabulary', level: 0, character: 'ふ', readings: ['fu'], meanings: ['FU'], explanation: 'Hiragana: fu' },
  { id: 'kana-h29', type: 'vocabulary', level: 0, character: 'へ', readings: ['he'], meanings: ['HE'], explanation: 'Hiragana: he' },
  { id: 'kana-h30', type: 'vocabulary', level: 0, character: 'ほ', readings: ['ho'], meanings: ['HO'], explanation: 'Hiragana: ho' },
  { id: 'kana-h31', type: 'vocabulary', level: 0, character: 'ま', readings: ['ma'], meanings: ['MA'], explanation: 'Hiragana: ma' },
  { id: 'kana-h32', type: 'vocabulary', level: 0, character: 'み', readings: ['mi'], meanings: ['MI'], explanation: 'Hiragana: mi' },
  { id: 'kana-h33', type: 'vocabulary', level: 0, character: 'む', readings: ['mu'], meanings: ['MU'], explanation: 'Hiragana: mu' },
  { id: 'kana-h34', type: 'vocabulary', level: 0, character: 'め', readings: ['me'], meanings: ['ME'], explanation: 'Hiragana: me' },
  { id: 'kana-h35', type: 'vocabulary', level: 0, character: 'も', readings: ['mo'], meanings: ['MO'], explanation: 'Hiragana: mo' },
  { id: 'kana-h36', type: 'vocabulary', level: 0, character: 'や', readings: ['ya'], meanings: ['YA'], explanation: 'Hiragana: ya' },
  { id: 'kana-h37', type: 'vocabulary', level: 0, character: 'ゆ', readings: ['yu'], meanings: ['YU'], explanation: 'Hiragana: yu' },
  { id: 'kana-h38', type: 'vocabulary', level: 0, character: 'よ', readings: ['yo'], meanings: ['YO'], explanation: 'Hiragana: yo' },
  { id: 'kana-h39', type: 'vocabulary', level: 0, character: 'ら', readings: ['ra'], meanings: ['RA'], explanation: 'Hiragana: ra' },
  { id: 'kana-h40', type: 'vocabulary', level: 0, character: 'り', readings: ['ri'], meanings: ['RI'], explanation: 'Hiragana: ri' },
  { id: 'kana-h41', type: 'vocabulary', level: 0, character: 'る', readings: ['ru'], meanings: ['RU'], explanation: 'Hiragana: ru' },
  { id: 'kana-h42', type: 'vocabulary', level: 0, character: 'れ', readings: ['re'], meanings: ['RE'], explanation: 'Hiragana: re' },
  { id: 'kana-h43', type: 'vocabulary', level: 0, character: 'ろ', readings: ['ro'], meanings: ['RO'], explanation: 'Hiragana: ro' },
  { id: 'kana-h44', type: 'vocabulary', level: 0, character: 'わ', readings: ['wa'], meanings: ['WA'], explanation: 'Hiragana: wa' },
  { id: 'kana-h45', type: 'vocabulary', level: 0, character: 'を', readings: ['wo'], meanings: ['WO'], explanation: 'Hiragana: wo' },
  { id: 'kana-h46', type: 'vocabulary', level: 0, character: 'ん', readings: ['n'], meanings: ['N'], explanation: 'Hiragana: n' }
];

export const katakana: Item[] = [
  { id: 'kana-k1', type: 'vocabulary', level: 0, character: 'ア', readings: ['a'], meanings: ['A'], explanation: 'Katakana: a' },
  { id: 'kana-k2', type: 'vocabulary', level: 0, character: 'イ', readings: ['i'], meanings: ['I'], explanation: 'Katakana: i' },
  { id: 'kana-k3', type: 'vocabulary', level: 0, character: 'ウ', readings: ['u'], meanings: ['U'], explanation: 'Katakana: u' },
  { id: 'kana-k4', type: 'vocabulary', level: 0, character: 'エ', readings: ['e'], meanings: ['E'], explanation: 'Katakana: e' },
  { id: 'kana-k5', type: 'vocabulary', level: 0, character: 'オ', readings: ['o'], meanings: ['O'], explanation: 'Katakana: o' },
  { id: 'kana-k6', type: 'vocabulary', level: 0, character: 'カ', readings: ['ka'], meanings: ['KA'], explanation: 'Katakana: ka' },
  { id: 'kana-k7', type: 'vocabulary', level: 0, character: 'キ', readings: ['ki'], meanings: ['KI'], explanation: 'Katakana: ki' },
  { id: 'kana-k8', type: 'vocabulary', level: 0, character: 'ク', readings: ['ku'], meanings: ['KU'], explanation: 'Katakana: ku' },
  { id: 'kana-k9', type: 'vocabulary', level: 0, character: 'ケ', readings: ['ke'], meanings: ['KE'], explanation: 'Katakana: ke' },
  { id: 'kana-k10', type: 'vocabulary', level: 0, character: 'コ', readings: ['ko'], meanings: ['KO'], explanation: 'Katakana: ko' },
  { id: 'kana-k11', type: 'vocabulary', level: 0, character: 'サ', readings: ['sa'], meanings: ['SA'], explanation: 'Katakana: sa' },
  { id: 'kana-k12', type: 'vocabulary', level: 0, character: 'シ', readings: ['shi'], meanings: ['SHI'], explanation: 'Katakana: shi' },
  { id: 'kana-k13', type: 'vocabulary', level: 0, character: 'ス', readings: ['su'], meanings: ['SU'], explanation: 'Katakana: su' },
  { id: 'kana-k14', type: 'vocabulary', level: 0, character: 'セ', readings: ['se'], meanings: ['SE'], explanation: 'Katakana: se' },
  { id: 'kana-k15', type: 'vocabulary', level: 0, character: 'ソ', readings: ['so'], meanings: ['SO'], explanation: 'Katakana: so' },
  { id: 'kana-k16', type: 'vocabulary', level: 0, character: 'タ', readings: ['ta'], meanings: ['TA'], explanation: 'Katakana: ta' },
  { id: 'kana-k17', type: 'vocabulary', level: 0, character: 'チ', readings: ['chi'], meanings: ['CHI'], explanation: 'Katakana: chi' },
  { id: 'kana-k18', type: 'vocabulary', level: 0, character: 'ツ', readings: ['tsu'], meanings: ['TSU'], explanation: 'Katakana: tsu' },
  { id: 'kana-k19', type: 'vocabulary', level: 0, character: 'テ', readings: ['te'], meanings: ['TE'], explanation: 'Katakana: te' },
  { id: 'kana-k20', type: 'vocabulary', level: 0, character: 'ト', readings: ['to'], meanings: ['TO'], explanation: 'Katakana: to' },
  { id: 'kana-k21', type: 'vocabulary', level: 0, character: 'ナ', readings: ['na'], meanings: ['NA'], explanation: 'Katakana: na' },
  { id: 'kana-k22', type: 'vocabulary', level: 0, character: 'ニ', readings: ['ni'], meanings: ['NI'], explanation: 'Katakana: ni' },
  { id: 'kana-k23', type: 'vocabulary', level: 0, character: 'ヌ', readings: ['nu'], meanings: ['NU'], explanation: 'Katakana: nu' },
  { id: 'kana-k24', type: 'vocabulary', level: 0, character: 'ネ', readings: ['ne'], meanings: ['NE'], explanation: 'Katakana: ne' },
  { id: 'kana-k25', type: 'vocabulary', level: 0, character: 'ノ', readings: ['no'], meanings: ['NO'], explanation: 'Katakana: no' },
  { id: 'kana-k26', type: 'vocabulary', level: 0, character: 'ハ', readings: ['ha'], meanings: ['HA'], explanation: 'Katakana: ha' },
  { id: 'kana-k27', type: 'vocabulary', level: 0, character: 'ヒ', readings: ['hi'], meanings: ['HI'], explanation: 'Katakana: hi' },
  { id: 'kana-k28', type: 'vocabulary', level: 0, character: 'フ', readings: ['fu'], meanings: ['FU'], explanation: 'Katakana: fu' },
  { id: 'kana-k29', type: 'vocabulary', level: 0, character: 'ヘ', readings: ['he'], meanings: ['HE'], explanation: 'Katakana: he' },
  { id: 'kana-k30', type: 'vocabulary', level: 0, character: 'ホ', readings: ['ho'], meanings: ['HO'], explanation: 'Katakana: ho' },
  { id: 'kana-k31', type: 'vocabulary', level: 0, character: 'マ', readings: ['ma'], meanings: ['MA'], explanation: 'Katakana: ma' },
  { id: 'kana-k32', type: 'vocabulary', level: 0, character: 'ミ', readings: ['mi'], meanings: ['MI'], explanation: 'Katakana: mi' },
  { id: 'kana-k33', type: 'vocabulary', level: 0, character: 'ム', readings: ['mu'], meanings: ['MU'], explanation: 'Katakana: mu' },
  { id: 'kana-k34', type: 'vocabulary', level: 0, character: 'メ', readings: ['me'], meanings: ['ME'], explanation: 'Katakana: me' },
  { id: 'kana-k35', type: 'vocabulary', level: 0, character: 'モ', readings: ['mo'], meanings: ['MO'], explanation: 'Katakana: mo' },
  { id: 'kana-k36', type: 'vocabulary', level: 0, character: 'ヤ', readings: ['ya'], meanings: ['YA'], explanation: 'Katakana: ya' },
  { id: 'kana-k37', type: 'vocabulary', level: 0, character: 'ユ', readings: ['yu'], meanings: ['YU'], explanation: 'Katakana: yu' },
  { id: 'kana-k38', type: 'vocabulary', level: 0, character: 'ヨ', readings: ['yo'], meanings: ['YO'], explanation: 'Katakana: yo' },
  { id: 'kana-k39', type: 'vocabulary', level: 0, character: 'ラ', readings: ['ra'], meanings: ['RA'], explanation: 'Katakana: ra' },
  { id: 'kana-k40', type: 'vocabulary', level: 0, character: 'リ', readings: ['ri'], meanings: ['RI'], explanation: 'Katakana: ri' },
  { id: 'kana-k41', type: 'vocabulary', level: 0, character: 'ル', readings: ['ru'], meanings: ['RU'], explanation: 'Katakana: ru' },
  { id: 'kana-k42', type: 'vocabulary', level: 0, character: 'レ', readings: ['re'], meanings: ['RE'], explanation: 'Katakana: re' },
  { id: 'kana-k43', type: 'vocabulary', level: 0, character: 'ロ', readings: ['ro'], meanings: ['RO'], explanation: 'Katakana: ro' },
  { id: 'kana-k44', type: 'vocabulary', level: 0, character: 'ワ', readings: ['wa'], meanings: ['WA'], explanation: 'Katakana: wa' },
  { id: 'kana-k45', type: 'vocabulary', level: 0, character: 'ヲ', readings: ['wo'], meanings: ['WO'], explanation: 'Katakana: wo' },
  { id: 'kana-k46', type: 'vocabulary', level: 0, character: 'ン', readings: ['n'], meanings: ['N'], explanation: 'Katakana: n' }
];

export const hiraganaExtended: Item[] = [
  // Dakuon
  { id: 'kana-he1', type: 'vocabulary', level: 0, character: 'が', readings: ['ga'], meanings: ['GA'], explanation: 'Hiragana Extended: ga' },
  { id: 'kana-he2', type: 'vocabulary', level: 0, character: 'ぎ', readings: ['gi'], meanings: ['GI'], explanation: 'Hiragana Extended: gi' },
  { id: 'kana-he3', type: 'vocabulary', level: 0, character: 'ぐ', readings: ['gu'], meanings: ['GU'], explanation: 'Hiragana Extended: gu' },
  { id: 'kana-he4', type: 'vocabulary', level: 0, character: 'げ', readings: ['ge'], meanings: ['GE'], explanation: 'Hiragana Extended: ge' },
  { id: 'kana-he5', type: 'vocabulary', level: 0, character: 'ご', readings: ['go'], meanings: ['GO'], explanation: 'Hiragana Extended: go' },
  { id: 'kana-he6', type: 'vocabulary', level: 0, character: 'ざ', readings: ['za'], meanings: ['ZA'], explanation: 'Hiragana Extended: za' },
  { id: 'kana-he7', type: 'vocabulary', level: 0, character: 'じ', readings: ['ji'], meanings: ['JI'], explanation: 'Hiragana Extended: ji' },
  { id: 'kana-he8', type: 'vocabulary', level: 0, character: 'ず', readings: ['zu'], meanings: ['ZU'], explanation: 'Hiragana Extended: zu' },
  { id: 'kana-he9', type: 'vocabulary', level: 0, character: 'ぜ', readings: ['ze'], meanings: ['ZE'], explanation: 'Hiragana Extended: ze' },
  { id: 'kana-he10', type: 'vocabulary', level: 0, character: 'ぞ', readings: ['zo'], meanings: ['ZO'], explanation: 'Hiragana Extended: zo' },
  { id: 'kana-he11', type: 'vocabulary', level: 0, character: 'だ', readings: ['da'], meanings: ['DA'], explanation: 'Hiragana Extended: da' },
  { id: 'kana-he12', type: 'vocabulary', level: 0, character: 'ぢ', readings: ['ji'], meanings: ['JI'], explanation: 'Hiragana Extended: ji (rare)' },
  { id: 'kana-he13', type: 'vocabulary', level: 0, character: 'づ', readings: ['zu'], meanings: ['ZU'], explanation: 'Hiragana Extended: zu (rare)' },
  { id: 'kana-he14', type: 'vocabulary', level: 0, character: 'で', readings: ['de'], meanings: ['DE'], explanation: 'Hiragana Extended: de' },
  { id: 'kana-he15', type: 'vocabulary', level: 0, character: 'ど', readings: ['do'], meanings: ['DO'], explanation: 'Hiragana Extended: do' },
  { id: 'kana-he16', type: 'vocabulary', level: 0, character: 'ば', readings: ['ba'], meanings: ['BA'], explanation: 'Hiragana Extended: ba' },
  { id: 'kana-he17', type: 'vocabulary', level: 0, character: 'び', readings: ['bi'], meanings: ['BI'], explanation: 'Hiragana Extended: bi' },
  { id: 'kana-he18', type: 'vocabulary', level: 0, character: 'ぶ', readings: ['bu'], meanings: ['BU'], explanation: 'Hiragana Extended: bu' },
  { id: 'kana-he19', type: 'vocabulary', level: 0, character: 'べ', readings: ['be'], meanings: ['BE'], explanation: 'Hiragana Extended: be' },
  { id: 'kana-he20', type: 'vocabulary', level: 0, character: 'ぼ', readings: ['bo'], meanings: ['BO'], explanation: 'Hiragana Extended: bo' },
  // Handakuon
  { id: 'kana-he21', type: 'vocabulary', level: 0, character: 'ぱ', readings: ['pa'], meanings: ['PA'], explanation: 'Hiragana Extended: pa' },
  { id: 'kana-he22', type: 'vocabulary', level: 0, character: 'ぴ', readings: ['pi'], meanings: ['PI'], explanation: 'Hiragana Extended: pi' },
  { id: 'kana-he23', type: 'vocabulary', level: 0, character: 'ぷ', readings: ['pu'], meanings: ['PU'], explanation: 'Hiragana Extended: pu' },
  { id: 'kana-he24', type: 'vocabulary', level: 0, character: 'ぺ', readings: ['pe'], meanings: ['PE'], explanation: 'Hiragana Extended: pe' },
  { id: 'kana-he25', type: 'vocabulary', level: 0, character: 'ぽ', readings: ['po'], meanings: ['PO'], explanation: 'Hiragana Extended: po' },
  // Yōon
  { id: 'kana-he26', type: 'vocabulary', level: 0, character: 'きゃ', readings: ['kya'], meanings: ['KYA'], explanation: 'Hiragana Extended: kya' },
  { id: 'kana-he27', type: 'vocabulary', level: 0, character: 'きゅ', readings: ['kyu'], meanings: ['KYU'], explanation: 'Hiragana Extended: kyu' },
  { id: 'kana-he28', type: 'vocabulary', level: 0, character: 'きょ', readings: ['kyo'], meanings: ['KYO'], explanation: 'Hiragana Extended: kyo' },
  { id: 'kana-he29', type: 'vocabulary', level: 0, character: 'しゃ', readings: ['sha'], meanings: ['SHA'], explanation: 'Hiragana Extended: sha' },
  { id: 'kana-he30', type: 'vocabulary', level: 0, character: 'しゅ', readings: ['shu'], meanings: ['SHU'], explanation: 'Hiragana Extended: shu' },
  { id: 'kana-he31', type: 'vocabulary', level: 0, character: 'しょ', readings: ['sho'], meanings: ['SHO'], explanation: 'Hiragana Extended: sho' },
  { id: 'kana-he32', type: 'vocabulary', level: 0, character: 'ちゃ', readings: ['cha'], meanings: ['CHA'], explanation: 'Hiragana Extended: cha' },
  { id: 'kana-he33', type: 'vocabulary', level: 0, character: 'ちゅ', readings: ['chu'], meanings: ['CHU'], explanation: 'Hiragana Extended: chu' },
  { id: 'kana-he34', type: 'vocabulary', level: 0, character: 'ちょ', readings: ['cho'], meanings: ['CHO'], explanation: 'Hiragana Extended: cho' },
  { id: 'kana-he35', type: 'vocabulary', level: 0, character: 'にゃ', readings: ['nya'], meanings: ['NYA'], explanation: 'Hiragana Extended: nya' },
  { id: 'kana-he36', type: 'vocabulary', level: 0, character: 'にゅ', readings: ['nyu'], meanings: ['NYU'], explanation: 'Hiragana Extended: nyu' },
  { id: 'kana-he37', type: 'vocabulary', level: 0, character: 'にょ', readings: ['nyo'], meanings: ['NYO'], explanation: 'Hiragana Extended: nyo' },
  { id: 'kana-he38', type: 'vocabulary', level: 0, character: 'ひゃ', readings: ['hya'], meanings: ['HYA'], explanation: 'Hiragana Extended: hya' },
  { id: 'kana-he39', type: 'vocabulary', level: 0, character: 'ひゅ', readings: ['hyu'], meanings: ['HYU'], explanation: 'Hiragana Extended: hyu' },
  { id: 'kana-he40', type: 'vocabulary', level: 0, character: 'ひょ', readings: ['hyo'], meanings: ['HYO'], explanation: 'Hiragana Extended: hyo' },
  { id: 'kana-he41', type: 'vocabulary', level: 0, character: 'みゃ', readings: ['mya'], meanings: ['MYA'], explanation: 'Hiragana Extended: mya' },
  { id: 'kana-he42', type: 'vocabulary', level: 0, character: 'みゅ', readings: ['myu'], meanings: ['MYU'], explanation: 'Hiragana Extended: myu' },
  { id: 'kana-he43', type: 'vocabulary', level: 0, character: 'みょ', readings: ['myo'], meanings: ['MYO'], explanation: 'Hiragana Extended: myo' },
  { id: 'kana-he44', type: 'vocabulary', level: 0, character: 'りゃ', readings: ['rya'], meanings: ['RYA'], explanation: 'Hiragana Extended: rya' },
  { id: 'kana-he45', type: 'vocabulary', level: 0, character: 'りゅ', readings: ['ryu'], meanings: ['RYU'], explanation: 'Hiragana Extended: ryu' },
  { id: 'kana-he46', type: 'vocabulary', level: 0, character: 'りょ', readings: ['ryo'], meanings: ['RYO'], explanation: 'Hiragana Extended: ryo' },
  { id: 'kana-he47', type: 'vocabulary', level: 0, character: 'ぎゃ', readings: ['gya'], meanings: ['GYA'], explanation: 'Hiragana Extended: gya' },
  { id: 'kana-he48', type: 'vocabulary', level: 0, character: 'ぎゅ', readings: ['gyu'], meanings: ['GYU'], explanation: 'Hiragana Extended: gyu' },
  { id: 'kana-he49', type: 'vocabulary', level: 0, character: 'ぎょ', readings: ['gyo'], meanings: ['GYO'], explanation: 'Hiragana Extended: gyo' },
  { id: 'kana-he50', type: 'vocabulary', level: 0, character: 'じゃ', readings: ['ja'], meanings: ['JA'], explanation: 'Hiragana Extended: ja' },
  { id: 'kana-he51', type: 'vocabulary', level: 0, character: 'じゅ', readings: ['ju'], meanings: ['JU'], explanation: 'Hiragana Extended: ju' },
  { id: 'kana-he52', type: 'vocabulary', level: 0, character: 'じょ', readings: ['jo'], meanings: ['JO'], explanation: 'Hiragana Extended: jo' },
  { id: 'kana-he53', type: 'vocabulary', level: 0, character: 'びゃ', readings: ['bya'], meanings: ['BYA'], explanation: 'Hiragana Extended: bya' },
  { id: 'kana-he54', type: 'vocabulary', level: 0, character: 'びゅ', readings: ['byu'], meanings: ['BYU'], explanation: 'Hiragana Extended: byu' },
  { id: 'kana-he55', type: 'vocabulary', level: 0, character: 'びょ', readings: ['byo'], meanings: ['BYO'], explanation: 'Hiragana Extended: byo' },
  { id: 'kana-he56', type: 'vocabulary', level: 0, character: 'ぴゃ', readings: ['pya'], meanings: ['PYA'], explanation: 'Hiragana Extended: pya' },
  { id: 'kana-he57', type: 'vocabulary', level: 0, character: 'ぴゅ', readings: ['pyu'], meanings: ['PYU'], explanation: 'Hiragana Extended: pyu' },
  { id: 'kana-he58', type: 'vocabulary', level: 0, character: 'ぴょ', readings: ['pyo'], meanings: ['PYO'], explanation: 'Hiragana Extended: pyo' }
];

export const katakanaExtended: Item[] = [
  // Dakuon
  { id: 'kana-ke1', type: 'vocabulary', level: 0, character: 'ガ', readings: ['ga'], meanings: ['GA'], explanation: 'Katakana Extended: ga' },
  { id: 'kana-ke2', type: 'vocabulary', level: 0, character: 'ギ', readings: ['gi'], meanings: ['GI'], explanation: 'Katakana Extended: gi' },
  { id: 'kana-ke3', type: 'vocabulary', level: 0, character: 'グ', readings: ['gu'], meanings: ['GU'], explanation: 'Katakana Extended: gu' },
  { id: 'kana-ke4', type: 'vocabulary', level: 0, character: 'ゲ', readings: ['ge'], meanings: ['GE'], explanation: 'Katakana Extended: ge' },
  { id: 'kana-ke5', type: 'vocabulary', level: 0, character: 'ゴ', readings: ['go'], meanings: ['GO'], explanation: 'Katakana Extended: go' },
  { id: 'kana-ke6', type: 'vocabulary', level: 0, character: 'ザ', readings: ['za'], meanings: ['ZA'], explanation: 'Katakana Extended: za' },
  { id: 'kana-ke7', type: 'vocabulary', level: 0, character: 'ジ', readings: ['ji'], meanings: ['JI'], explanation: 'Katakana Extended: ji' },
  { id: 'kana-ke8', type: 'vocabulary', level: 0, character: 'ズ', readings: ['zu'], meanings: ['ZU'], explanation: 'Katakana Extended: zu' },
  { id: 'kana-ke9', type: 'vocabulary', level: 0, character: 'ゼ', readings: ['ze'], meanings: ['ZE'], explanation: 'Katakana Extended: ze' },
  { id: 'kana-ke10', type: 'vocabulary', level: 0, character: 'ゾ', readings: ['zo'], meanings: ['ZO'], explanation: 'Katakana Extended: zo' },
  { id: 'kana-ke11', type: 'vocabulary', level: 0, character: 'ダ', readings: ['da'], meanings: ['DA'], explanation: 'Katakana Extended: da' },
  { id: 'kana-ke12', type: 'vocabulary', level: 0, character: 'ヂ', readings: ['ji'], meanings: ['JI'], explanation: 'Katakana Extended: ji (rare)' },
  { id: 'kana-ke13', type: 'vocabulary', level: 0, character: 'ヅ', readings: ['zu'], meanings: ['ZU'], explanation: 'Katakana Extended: zu (rare)' },
  { id: 'kana-ke14', type: 'vocabulary', level: 0, character: 'デ', readings: ['de'], meanings: ['DE'], explanation: 'Katakana Extended: de' },
  { id: 'kana-ke15', type: 'vocabulary', level: 0, character: 'ド', readings: ['do'], meanings: ['DO'], explanation: 'Katakana Extended: do' },
  { id: 'kana-ke16', type: 'vocabulary', level: 0, character: 'バ', readings: ['ba'], meanings: ['BA'], explanation: 'Katakana Extended: ba' },
  { id: 'kana-ke17', type: 'vocabulary', level: 0, character: 'ビ', readings: ['bi'], meanings: ['BI'], explanation: 'Katakana Extended: bi' },
  { id: 'kana-ke18', type: 'vocabulary', level: 0, character: 'ブ', readings: ['bu'], meanings: ['BU'], explanation: 'Katakana Extended: bu' },
  { id: 'kana-ke19', type: 'vocabulary', level: 0, character: 'ベ', readings: ['be'], meanings: ['BE'], explanation: 'Katakana Extended: be' },
  { id: 'kana-ke20', type: 'vocabulary', level: 0, character: 'ボ', readings: ['bo'], meanings: ['BO'], explanation: 'Katakana Extended: bo' },
  // Handakuon
  { id: 'kana-ke21', type: 'vocabulary', level: 0, character: 'パ', readings: ['pa'], meanings: ['PA'], explanation: 'Katakana Extended: pa' },
  { id: 'kana-ke22', type: 'vocabulary', level: 0, character: 'ピ', readings: ['pi'], meanings: ['PI'], explanation: 'Katakana Extended: pi' },
  { id: 'kana-ke23', type: 'vocabulary', level: 0, character: 'プ', readings: ['pu'], meanings: ['PU'], explanation: 'Katakana Extended: pu' },
  { id: 'kana-ke24', type: 'vocabulary', level: 0, character: 'ペ', readings: ['pe'], meanings: ['PE'], explanation: 'Katakana Extended: pe' },
  { id: 'kana-ke25', type: 'vocabulary', level: 0, character: 'ポ', readings: ['po'], meanings: ['PO'], explanation: 'Katakana Extended: po' },
  // Yōon
  { id: 'kana-ke26', type: 'vocabulary', level: 0, character: 'キャ', readings: ['kya'], meanings: ['KYA'], explanation: 'Katakana Extended: kya' },
  { id: 'kana-ke27', type: 'vocabulary', level: 0, character: 'キュ', readings: ['kyu'], meanings: ['KYU'], explanation: 'Katakana Extended: kyu' },
  { id: 'kana-ke28', type: 'vocabulary', level: 0, character: 'キョ', readings: ['kyo'], meanings: ['KYO'], explanation: 'Katakana Extended: kyo' },
  { id: 'kana-ke29', type: 'vocabulary', level: 0, character: 'シャ', readings: ['sha'], meanings: ['SHA'], explanation: 'Katakana Extended: sha' },
  { id: 'kana-ke30', type: 'vocabulary', level: 0, character: 'シュ', readings: ['shu'], meanings: ['SHU'], explanation: 'Katakana Extended: shu' },
  { id: 'kana-ke31', type: 'vocabulary', level: 0, character: 'ショ', readings: ['sho'], meanings: ['SHO'], explanation: 'Katakana Extended: sho' },
  { id: 'kana-ke32', type: 'vocabulary', level: 0, character: 'チャ', readings: ['cha'], meanings: ['CHA'], explanation: 'Katakana Extended: cha' },
  { id: 'kana-ke33', type: 'vocabulary', level: 0, character: 'チュ', readings: ['chu'], meanings: ['CHU'], explanation: 'Katakana Extended: chu' },
  { id: 'kana-ke34', type: 'vocabulary', level: 0, character: 'チョ', readings: ['cho'], meanings: ['CHO'], explanation: 'Katakana Extended: cho' },
  { id: 'kana-ke35', type: 'vocabulary', level: 0, character: 'ニャ', readings: ['nya'], meanings: ['NYA'], explanation: 'Katakana Extended: nya' },
  { id: 'kana-ke36', type: 'vocabulary', level: 0, character: 'ニュ', readings: ['nyu'], meanings: ['NYU'], explanation: 'Katakana Extended: nyu' },
  { id: 'kana-ke37', type: 'vocabulary', level: 0, character: 'ニョ', readings: ['nyo'], meanings: ['NYO'], explanation: 'Katakana Extended: nyo' },
  { id: 'kana-ke38', type: 'vocabulary', level: 0, character: 'ヒャ', readings: ['hya'], meanings: ['HYA'], explanation: 'Katakana Extended: hya' },
  { id: 'kana-ke39', type: 'vocabulary', level: 0, character: 'ヒュ', readings: ['hyu'], meanings: ['HYU'], explanation: 'Katakana Extended: hyu' },
  { id: 'kana-ke40', type: 'vocabulary', level: 0, character: 'ヒョ', readings: ['hyo'], meanings: ['HYO'], explanation: 'Katakana Extended: hyo' },
  { id: 'kana-ke41', type: 'vocabulary', level: 0, character: 'ミャ', readings: ['mya'], meanings: ['MYA'], explanation: 'Katakana Extended: mya' },
  { id: 'kana-ke42', type: 'vocabulary', level: 0, character: 'ミュ', readings: ['myu'], meanings: ['MYU'], explanation: 'Katakana Extended: myu' },
  { id: 'kana-ke43', type: 'vocabulary', level: 0, character: 'ミョ', readings: ['myo'], meanings: ['MYO'], explanation: 'Katakana Extended: myo' },
  { id: 'kana-ke44', type: 'vocabulary', level: 0, character: 'リャ', readings: ['rya'], meanings: ['RYA'], explanation: 'Katakana Extended: rya' },
  { id: 'kana-ke45', type: 'vocabulary', level: 0, character: 'リュ', readings: ['ryu'], meanings: ['RYU'], explanation: 'Katakana Extended: ryu' },
  { id: 'kana-ke46', type: 'vocabulary', level: 0, character: 'リョ', readings: ['ryo'], meanings: ['RYO'], explanation: 'Katakana Extended: ryo' },
  { id: 'kana-ke47', type: 'vocabulary', level: 0, character: 'ギャ', readings: ['gya'], meanings: ['GYA'], explanation: 'Katakana Extended: gya' },
  { id: 'kana-ke48', type: 'vocabulary', level: 0, character: 'ギュ', readings: ['gyu'], meanings: ['GYU'], explanation: 'Katakana Extended: gyu' },
  { id: 'kana-ke49', type: 'vocabulary', level: 0, character: 'ギョ', readings: ['gyo'], meanings: ['GYO'], explanation: 'Katakana Extended: gyo' },
  { id: 'kana-ke50', type: 'vocabulary', level: 0, character: 'ジャ', readings: ['ja'], meanings: ['JA'], explanation: 'Katakana Extended: ja' },
  { id: 'kana-ke51', type: 'vocabulary', level: 0, character: 'ジュ', readings: ['ju'], meanings: ['JU'], explanation: 'Katakana Extended: ju' },
  { id: 'kana-ke52', type: 'vocabulary', level: 0, character: 'ジョ', readings: ['jo'], meanings: ['JO'], explanation: 'Katakana Extended: jo' },
  { id: 'kana-ke53', type: 'vocabulary', level: 0, character: 'ビャ', readings: ['bya'], meanings: ['BYA'], explanation: 'Katakana Extended: bya' },
  { id: 'kana-ke54', type: 'vocabulary', level: 0, character: 'ビュ', readings: ['byu'], meanings: ['BYU'], explanation: 'Katakana Extended: byu' },
  { id: 'kana-ke55', type: 'vocabulary', level: 0, character: 'ビョ', readings: ['byo'], meanings: ['BYO'], explanation: 'Katakana Extended: byo' },
  { id: 'kana-ke56', type: 'vocabulary', level: 0, character: 'ピャ', readings: ['pya'], meanings: ['PYA'], explanation: 'Katakana Extended: pya' },
  { id: 'kana-ke57', type: 'vocabulary', level: 0, character: 'ピュ', readings: ['pyu'], meanings: ['PYU'], explanation: 'Katakana Extended: pyu' },
  { id: 'kana-ke58', type: 'vocabulary', level: 0, character: 'ピョ', readings: ['pyo'], meanings: ['PYO'], explanation: 'Katakana Extended: pyo' }
];
